### ISSUE TITLE
InaccessibleObjectException / Java 16 not working

### ISSUE THREAD

**Issue by djnejk** [ServerJars/updater#13] opened 2021-06-17 21:15 UTC
Hello,
If I start the server using java 16 I getting error
![image](https://user-images.githubusercontent.com/61634734/122473240-db4fa600-cfc1-11eb-97a9-58f592508190.png)

**Comment by SpraxDev** [comment] 2021-06-18 11:18
Duplicate of #12

A fix is release in the coming week fixing a bunch of stuff (including Java 16).

**Comment by SpraxDev** [comment] 2021-06-24 12:39
Please download the new updater version. This issue has been fixed

**Closed as completed by SpraxDev** 2021-06-24 12:39 UTC
Labels: bug, duplicate
